# 定义PHP基础来源
FROM registry.cn-beijing.aliyuncs.com/rdisme/php:7.2-fpm-0.0.0

# 安装PHPRedis扩展
RUN cd ~ \
    && curl -L -o 4.2.0.tar.gz https://github.com/phpredis/phpredis/archive/4.2.0.tar.gz \
    && tar -zxvf 4.2.0.tar.gz \
    && rm -rf 4.2.0.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-4.2.0 /usr/src/php/ext/redis \
    && docker-php-ext-install redis