# 定义PHP基础来源
FROM registry.cn-beijing.aliyuncs.com/rdisme/php:7.2-fpm-0.0.0.0

# 安装swoole扩展
RUN cd ~ \
    && curl -L -o v4.2.12.tar.gz https://github.com/swoole/swoole-src/archive/v4.2.12.tar.gz \
    && tar -zxvf v4.2.12.tar.gz \
    && rm -rf v4.2.12.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv swoole-src-4.2.12 /usr/src/php/ext/swoole \
    && docker-php-ext-install swoole